/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as JoinRouteImport } from './routes/join'
import { Route as MediaRouteImport } from './routes/media'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminAcademyRouteRouteImport } from './routes/_authenticated/admin/academy/route'
import { Route as AuthenticatedAdminBranchesRouteImport } from './routes/_authenticated/admin/branches'
import { Route as AuthenticatedAdminCoursesRouteImport } from './routes/_authenticated/admin/courses'
import { Route as AuthenticatedAdminMediaRouteImport } from './routes/_authenticated/admin/media'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated/admin/notifications'
import { Route as AuthenticatedAdminPartnersRouteImport } from './routes/_authenticated/admin/partners'
import { Route as AuthenticatedAdminPipelineRouteImport } from './routes/_authenticated/admin/pipeline'
import { Route as AuthenticatedAdminPostsRouteImport } from './routes/_authenticated/admin/posts'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin/reports'
import { Route as AuthenticatedAdminSeasonsRouteImport } from './routes/_authenticated/admin/seasons'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminSubmissionsRouteImport } from './routes/_authenticated/admin/submissions'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminAcademyIndexRouteImport } from './routes/_authenticated/admin/academy/index'
import { Route as AuthenticatedAdminAcademyAiAgentsRouteImport } from './routes/_authenticated/admin/academy/ai-agents'
import { Route as AuthenticatedAdminAcademyAnalyticsRouteImport } from './routes/_authenticated/admin/academy/analytics'
import { Route as AuthenticatedAdminAcademyAssessmentsRouteImport } from './routes/_authenticated/admin/academy/assessments'
import { Route as AuthenticatedAdminAcademyAttendanceRouteImport } from './routes/_authenticated/admin/academy/attendance'
import { Route as AuthenticatedAdminAcademyBranchReportsRouteImport } from './routes/_authenticated/admin/academy/branch-reports'
import { Route as AuthenticatedAdminAcademyBranchesRouteImport } from './routes/_authenticated/admin/academy/branches'
import { Route as AuthenticatedAdminAcademyCapacityRouteImport } from './routes/_authenticated/admin/academy/capacity'
import { Route as AuthenticatedAdminAcademyClientsRouteImport } from './routes/_authenticated/admin/academy/clients'
import { Route as AuthenticatedAdminAcademyCoachesRouteImport } from './routes/_authenticated/admin/academy/coaches'
import { Route as AuthenticatedAdminAcademyFinanceRouteImport } from './routes/_authenticated/admin/academy/finance'
import { Route as AuthenticatedAdminAcademyGroupsRouteImport } from './routes/_authenticated/admin/academy/groups'
import { Route as AuthenticatedAdminAcademyHrRouteImport } from './routes/_authenticated/admin/academy/hr'
import { Route as AuthenticatedAdminAcademyHrReportsRouteImport } from './routes/_authenticated/admin/academy/hr-reports'
import { Route as AuthenticatedAdminAcademyInventoryRouteImport } from './routes/_authenticated/admin/academy/inventory'
import { Route as AuthenticatedAdminAcademyLaneLogRouteImport } from './routes/_authenticated/admin/academy/lane-log'
import { Route as AuthenticatedAdminAcademyLanesRouteImport } from './routes/_authenticated/admin/academy/lanes'
import { Route as AuthenticatedAdminAcademyLeadsRouteImport } from './routes/_authenticated/admin/academy/leads'
import { Route as AuthenticatedAdminAcademyMaintenanceRouteImport } from './routes/_authenticated/admin/academy/maintenance'
import { Route as AuthenticatedAdminAcademyPermissionsRouteImport } from './routes/_authenticated/admin/academy/permissions'
import { Route as AuthenticatedAdminAcademyPoolOperationsRouteImport } from './routes/_authenticated/admin/academy/pool-operations'
import { Route as AuthenticatedAdminAcademyPoolsRouteImport } from './routes/_authenticated/admin/academy/pools'
import { Route as AuthenticatedAdminAcademyProcurementRouteImport } from './routes/_authenticated/admin/academy/procurement'
import { Route as AuthenticatedAdminAcademyQrAttendanceRouteImport } from './routes/_authenticated/admin/academy/qr-attendance'
import { Route as AuthenticatedAdminAcademyReceiptsRouteImport } from './routes/_authenticated/admin/academy/receipts'
import { Route as AuthenticatedAdminAcademyReportsRouteImport } from './routes/_authenticated/admin/academy/reports'
import { Route as AuthenticatedAdminAcademyScheduleRouteImport } from './routes/_authenticated/admin/academy/schedule'
import { Route as AuthenticatedAdminAcademySettingsRouteImport } from './routes/_authenticated/admin/academy/settings'
import { Route as AuthenticatedAdminAcademySubscriptionsRouteImport } from './routes/_authenticated/admin/academy/subscriptions'
import { Route as AuthenticatedAdminSettingsThemeRouteImport } from './routes/_authenticated/admin/settings.theme'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminAcademyRouteRoute =
  AuthenticatedAdminAcademyRouteRouteImport.update({
    id: '/academy',
    path: '/academy',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBranchesRoute =
  AuthenticatedAdminBranchesRouteImport.update({
    id: '/branches',
    path: '/branches',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCoursesRoute =
  AuthenticatedAdminCoursesRouteImport.update({
    id: '/courses',
    path: '/courses',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMediaRoute = AuthenticatedAdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPartnersRoute =
  AuthenticatedAdminPartnersRouteImport.update({
    id: '/partners',
    path: '/partners',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPipelineRoute =
  AuthenticatedAdminPipelineRouteImport.update({
    id: '/pipeline',
    path: '/pipeline',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPostsRoute = AuthenticatedAdminPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSeasonsRoute =
  AuthenticatedAdminSeasonsRouteImport.update({
    id: '/seasons',
    path: '/seasons',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSubmissionsRoute =
  AuthenticatedAdminSubmissionsRouteImport.update({
    id: '/submissions',
    path: '/submissions',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminAcademyIndexRoute =
  AuthenticatedAdminAcademyIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminAcademyRouteRoute,
  } as any)
const AuthenticatedAdminAcademyAiAgentsRoute =
  AuthenticatedAdminAcademyAiAgentsRouteImport.update({
    id: '/ai-agents',
    path: '/ai-agents',
    getParentRoute: () => AuthenticatedAdminAcademyRouteRoute,
  } as any)
const AuthenticatedAdminAcademyAnalyticsRoute =
  AuthenticatedAdminAcademyAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminAcademyRouteRoute,
  } as any)
const AuthenticatedAdminAcademyAssessmentsRoute =
  AuthenticatedAdminAcademyAssessmentsRouteImport.update({
    id: '/assessments',
    path: '/assessments',
    getParentRoute: () => AuthenticatedAdminAcademyRouteRoute,
  } as any)
const AuthenticatedAdminAcademyAttendanceRoute =
  AuthenticatedAdminAcademyAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => AuthenticatedAdminAcademyRouteRoute,
  } as any)
const AuthenticatedAdminAcademyBranchReportsRoute =
  AuthenticatedAdminAcademyBranchReportsRouteImport.update({
    id: '/branch-reports',
    path: '/branch-reports',
    getParentRoute: () => AuthenticatedAdminAcademyRouteRoute,
  } as any)
const AuthenticatedAdminAcademyBranchesRoute =
  AuthenticatedAdminAcademyBranchesRouteImport.update({
    id: '/branches',
    path: '/branches',
    getParentRoute: () => AuthenticatedAdminAcademyRouteRoute,
  } as any)
const AuthenticatedAdminAcademyCapacityRoute =
  AuthenticatedAdminAcademyCapacityRouteImport.update({
    id: '/capacity',
    path: '/capacity',
    getParentRoute: () => AuthenticatedAdminAcademyRouteRoute,
  } as any)
const AuthenticatedAdminAcademyClientsRoute =
  AuthenticatedAdminAcademyClientsRouteImport.update({
    id: '/clients',
    path: '/clients',
    getParentRoute: () => AuthenticatedAdminAcademyRouteRoute,
  } as any)
const AuthenticatedAdminAcademyCoachesRoute =
  AuthenticatedAdminAcademyCoachesRouteImport.update({
    id: '/coaches',
    path: '/coaches',
    getParentRoute: () => AuthenticatedAdminAcademyRouteRoute,
  } as any)
const AuthenticatedAdminAcademyFinanceRoute =
  AuthenticatedAdminAcademyFinanceRouteImport.update({
    id: '/finance',
    path: '/finance',
    getParentRoute: () => AuthenticatedAdminAcademyRouteRoute,
  } as any)
const AuthenticatedAdminAcademyGroupsRoute =
  AuthenticatedAdminAcademyGroupsRouteImport.update({
    id: '/groups',
    path: '/groups',
    getParentRoute: () => AuthenticatedAdminAcademyRouteRoute,
  } as any)
const AuthenticatedAdminAcademyHrRoute =
  AuthenticatedAdminAcademyHrRouteImport.update({
    id: '/hr',
    path: '/hr',
    getParentRoute: () => AuthenticatedAdminAcademyRouteRoute,
  } as any)
const AuthenticatedAdminAcademyHrReportsRoute =
  AuthenticatedAdminAcademyHrReportsRouteImport.update({
    id: '/hr-reports',
    path: '/hr-reports',
    getParentRoute: () => AuthenticatedAdminAcademyRouteRoute,
  } as any)
const AuthenticatedAdminAcademyInventoryRoute =
  AuthenticatedAdminAcademyInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => AuthenticatedAdminAcademyRouteRoute,
  } as any)
const AuthenticatedAdminAcademyLaneLogRoute =
  AuthenticatedAdminAcademyLaneLogRouteImport.update({
    id: '/lane-log',
    path: '/lane-log',
    getParentRoute: () => AuthenticatedAdminAcademyRouteRoute,
  } as any)
const AuthenticatedAdminAcademyLanesRoute =
  AuthenticatedAdminAcademyLanesRouteImport.update({
    id: '/lanes',
    path: '/lanes',
    getParentRoute: () => AuthenticatedAdminAcademyRouteRoute,
  } as any)
const AuthenticatedAdminAcademyLeadsRoute =
  AuthenticatedAdminAcademyLeadsRouteImport.update({
    id: '/leads',
    path: '/leads',
    getParentRoute: () => AuthenticatedAdminAcademyRouteRoute,
  } as any)
const AuthenticatedAdminAcademyMaintenanceRoute =
  AuthenticatedAdminAcademyMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => AuthenticatedAdminAcademyRouteRoute,
  } as any)
const AuthenticatedAdminAcademyPermissionsRoute =
  AuthenticatedAdminAcademyPermissionsRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => AuthenticatedAdminAcademyRouteRoute,
  } as any)
const AuthenticatedAdminAcademyPoolOperationsRoute =
  AuthenticatedAdminAcademyPoolOperationsRouteImport.update({
    id: '/pool-operations',
    path: '/pool-operations',
    getParentRoute: () => AuthenticatedAdminAcademyRouteRoute,
  } as any)
const AuthenticatedAdminAcademyPoolsRoute =
  AuthenticatedAdminAcademyPoolsRouteImport.update({
    id: '/pools',
    path: '/pools',
    getParentRoute: () => AuthenticatedAdminAcademyRouteRoute,
  } as any)
const AuthenticatedAdminAcademyProcurementRoute =
  AuthenticatedAdminAcademyProcurementRouteImport.update({
    id: '/procurement',
    path: '/procurement',
    getParentRoute: () => AuthenticatedAdminAcademyRouteRoute,
  } as any)
const AuthenticatedAdminAcademyQrAttendanceRoute =
  AuthenticatedAdminAcademyQrAttendanceRouteImport.update({
    id: '/qr-attendance',
    path: '/qr-attendance',
    getParentRoute: () => AuthenticatedAdminAcademyRouteRoute,
  } as any)
const AuthenticatedAdminAcademyReceiptsRoute =
  AuthenticatedAdminAcademyReceiptsRouteImport.update({
    id: '/receipts',
    path: '/receipts',
    getParentRoute: () => AuthenticatedAdminAcademyRouteRoute,
  } as any)
const AuthenticatedAdminAcademyReportsRoute =
  AuthenticatedAdminAcademyReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminAcademyRouteRoute,
  } as any)
const AuthenticatedAdminAcademyScheduleRoute =
  AuthenticatedAdminAcademyScheduleRouteImport.update({
    id: '/schedule',
    path: '/schedule',
    getParentRoute: () => AuthenticatedAdminAcademyRouteRoute,
  } as any)
const AuthenticatedAdminAcademySettingsRoute =
  AuthenticatedAdminAcademySettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminAcademyRouteRoute,
  } as any)
const AuthenticatedAdminAcademySubscriptionsRoute =
  AuthenticatedAdminAcademySubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => AuthenticatedAdminAcademyRouteRoute,
  } as any)
const AuthenticatedAdminSettingsThemeRoute =
  AuthenticatedAdminSettingsThemeRouteImport.update({
    id: '/theme',
    path: '/theme',
    getParentRoute: () => AuthenticatedAdminSettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/join': typeof JoinRoute
  '/media': typeof MediaRoute
  '/partners': typeof PartnersRoute
  '/programs': typeof ProgramsRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/admin/academy': typeof AuthenticatedAdminAcademyRouteRouteWithChildren
  '/admin/branches': typeof AuthenticatedAdminBranchesRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/partners': typeof AuthenticatedAdminPartnersRoute
  '/admin/pipeline': typeof AuthenticatedAdminPipelineRoute
  '/admin/posts': typeof AuthenticatedAdminPostsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/seasons': typeof AuthenticatedAdminSeasonsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRouteWithChildren
  '/admin/submissions': typeof AuthenticatedAdminSubmissionsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/academy/ai-agents': typeof AuthenticatedAdminAcademyAiAgentsRoute
  '/admin/academy/analytics': typeof AuthenticatedAdminAcademyAnalyticsRoute
  '/admin/academy/assessments': typeof AuthenticatedAdminAcademyAssessmentsRoute
  '/admin/academy/attendance': typeof AuthenticatedAdminAcademyAttendanceRoute
  '/admin/academy/branch-reports': typeof AuthenticatedAdminAcademyBranchReportsRoute
  '/admin/academy/branches': typeof AuthenticatedAdminAcademyBranchesRoute
  '/admin/academy/capacity': typeof AuthenticatedAdminAcademyCapacityRoute
  '/admin/academy/clients': typeof AuthenticatedAdminAcademyClientsRoute
  '/admin/academy/coaches': typeof AuthenticatedAdminAcademyCoachesRoute
  '/admin/academy/finance': typeof AuthenticatedAdminAcademyFinanceRoute
  '/admin/academy/groups': typeof AuthenticatedAdminAcademyGroupsRoute
  '/admin/academy/hr': typeof AuthenticatedAdminAcademyHrRoute
  '/admin/academy/hr-reports': typeof AuthenticatedAdminAcademyHrReportsRoute
  '/admin/academy/inventory': typeof AuthenticatedAdminAcademyInventoryRoute
  '/admin/academy/lane-log': typeof AuthenticatedAdminAcademyLaneLogRoute
  '/admin/academy/lanes': typeof AuthenticatedAdminAcademyLanesRoute
  '/admin/academy/leads': typeof AuthenticatedAdminAcademyLeadsRoute
  '/admin/academy/maintenance': typeof AuthenticatedAdminAcademyMaintenanceRoute
  '/admin/academy/permissions': typeof AuthenticatedAdminAcademyPermissionsRoute
  '/admin/academy/pool-operations': typeof AuthenticatedAdminAcademyPoolOperationsRoute
  '/admin/academy/pools': typeof AuthenticatedAdminAcademyPoolsRoute
  '/admin/academy/procurement': typeof AuthenticatedAdminAcademyProcurementRoute
  '/admin/academy/qr-attendance': typeof AuthenticatedAdminAcademyQrAttendanceRoute
  '/admin/academy/receipts': typeof AuthenticatedAdminAcademyReceiptsRoute
  '/admin/academy/reports': typeof AuthenticatedAdminAcademyReportsRoute
  '/admin/academy/schedule': typeof AuthenticatedAdminAcademyScheduleRoute
  '/admin/academy/settings': typeof AuthenticatedAdminAcademySettingsRoute
  '/admin/academy/subscriptions': typeof AuthenticatedAdminAcademySubscriptionsRoute
  '/admin/settings/theme': typeof AuthenticatedAdminSettingsThemeRoute
  '/admin/academy/': typeof AuthenticatedAdminAcademyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/join': typeof JoinRoute
  '/media': typeof MediaRoute
  '/partners': typeof PartnersRoute
  '/programs': typeof ProgramsRoute
  '/admin/branches': typeof AuthenticatedAdminBranchesRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/partners': typeof AuthenticatedAdminPartnersRoute
  '/admin/pipeline': typeof AuthenticatedAdminPipelineRoute
  '/admin/posts': typeof AuthenticatedAdminPostsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/seasons': typeof AuthenticatedAdminSeasonsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRouteWithChildren
  '/admin/submissions': typeof AuthenticatedAdminSubmissionsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/academy/ai-agents': typeof AuthenticatedAdminAcademyAiAgentsRoute
  '/admin/academy/analytics': typeof AuthenticatedAdminAcademyAnalyticsRoute
  '/admin/academy/assessments': typeof AuthenticatedAdminAcademyAssessmentsRoute
  '/admin/academy/attendance': typeof AuthenticatedAdminAcademyAttendanceRoute
  '/admin/academy/branch-reports': typeof AuthenticatedAdminAcademyBranchReportsRoute
  '/admin/academy/branches': typeof AuthenticatedAdminAcademyBranchesRoute
  '/admin/academy/capacity': typeof AuthenticatedAdminAcademyCapacityRoute
  '/admin/academy/clients': typeof AuthenticatedAdminAcademyClientsRoute
  '/admin/academy/coaches': typeof AuthenticatedAdminAcademyCoachesRoute
  '/admin/academy/finance': typeof AuthenticatedAdminAcademyFinanceRoute
  '/admin/academy/groups': typeof AuthenticatedAdminAcademyGroupsRoute
  '/admin/academy/hr': typeof AuthenticatedAdminAcademyHrRoute
  '/admin/academy/hr-reports': typeof AuthenticatedAdminAcademyHrReportsRoute
  '/admin/academy/inventory': typeof AuthenticatedAdminAcademyInventoryRoute
  '/admin/academy/lane-log': typeof AuthenticatedAdminAcademyLaneLogRoute
  '/admin/academy/lanes': typeof AuthenticatedAdminAcademyLanesRoute
  '/admin/academy/leads': typeof AuthenticatedAdminAcademyLeadsRoute
  '/admin/academy/maintenance': typeof AuthenticatedAdminAcademyMaintenanceRoute
  '/admin/academy/permissions': typeof AuthenticatedAdminAcademyPermissionsRoute
  '/admin/academy/pool-operations': typeof AuthenticatedAdminAcademyPoolOperationsRoute
  '/admin/academy/pools': typeof AuthenticatedAdminAcademyPoolsRoute
  '/admin/academy/procurement': typeof AuthenticatedAdminAcademyProcurementRoute
  '/admin/academy/qr-attendance': typeof AuthenticatedAdminAcademyQrAttendanceRoute
  '/admin/academy/receipts': typeof AuthenticatedAdminAcademyReceiptsRoute
  '/admin/academy/reports': typeof AuthenticatedAdminAcademyReportsRoute
  '/admin/academy/schedule': typeof AuthenticatedAdminAcademyScheduleRoute
  '/admin/academy/settings': typeof AuthenticatedAdminAcademySettingsRoute
  '/admin/academy/subscriptions': typeof AuthenticatedAdminAcademySubscriptionsRoute
  '/admin/settings/theme': typeof AuthenticatedAdminSettingsThemeRoute
  '/admin/academy': typeof AuthenticatedAdminAcademyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/join': typeof JoinRoute
  '/media': typeof MediaRoute
  '/partners': typeof PartnersRoute
  '/programs': typeof ProgramsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/admin/academy': typeof AuthenticatedAdminAcademyRouteRouteWithChildren
  '/_authenticated/admin/branches': typeof AuthenticatedAdminBranchesRoute
  '/_authenticated/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/_authenticated/admin/media': typeof AuthenticatedAdminMediaRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/partners': typeof AuthenticatedAdminPartnersRoute
  '/_authenticated/admin/pipeline': typeof AuthenticatedAdminPipelineRoute
  '/_authenticated/admin/posts': typeof AuthenticatedAdminPostsRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/seasons': typeof AuthenticatedAdminSeasonsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRouteWithChildren
  '/_authenticated/admin/submissions': typeof AuthenticatedAdminSubmissionsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/academy/ai-agents': typeof AuthenticatedAdminAcademyAiAgentsRoute
  '/_authenticated/admin/academy/analytics': typeof AuthenticatedAdminAcademyAnalyticsRoute
  '/_authenticated/admin/academy/assessments': typeof AuthenticatedAdminAcademyAssessmentsRoute
  '/_authenticated/admin/academy/attendance': typeof AuthenticatedAdminAcademyAttendanceRoute
  '/_authenticated/admin/academy/branch-reports': typeof AuthenticatedAdminAcademyBranchReportsRoute
  '/_authenticated/admin/academy/branches': typeof AuthenticatedAdminAcademyBranchesRoute
  '/_authenticated/admin/academy/capacity': typeof AuthenticatedAdminAcademyCapacityRoute
  '/_authenticated/admin/academy/clients': typeof AuthenticatedAdminAcademyClientsRoute
  '/_authenticated/admin/academy/coaches': typeof AuthenticatedAdminAcademyCoachesRoute
  '/_authenticated/admin/academy/finance': typeof AuthenticatedAdminAcademyFinanceRoute
  '/_authenticated/admin/academy/groups': typeof AuthenticatedAdminAcademyGroupsRoute
  '/_authenticated/admin/academy/hr': typeof AuthenticatedAdminAcademyHrRoute
  '/_authenticated/admin/academy/hr-reports': typeof AuthenticatedAdminAcademyHrReportsRoute
  '/_authenticated/admin/academy/inventory': typeof AuthenticatedAdminAcademyInventoryRoute
  '/_authenticated/admin/academy/lane-log': typeof AuthenticatedAdminAcademyLaneLogRoute
  '/_authenticated/admin/academy/lanes': typeof AuthenticatedAdminAcademyLanesRoute
  '/_authenticated/admin/academy/leads': typeof AuthenticatedAdminAcademyLeadsRoute
  '/_authenticated/admin/academy/maintenance': typeof AuthenticatedAdminAcademyMaintenanceRoute
  '/_authenticated/admin/academy/permissions': typeof AuthenticatedAdminAcademyPermissionsRoute
  '/_authenticated/admin/academy/pool-operations': typeof AuthenticatedAdminAcademyPoolOperationsRoute
  '/_authenticated/admin/academy/pools': typeof AuthenticatedAdminAcademyPoolsRoute
  '/_authenticated/admin/academy/procurement': typeof AuthenticatedAdminAcademyProcurementRoute
  '/_authenticated/admin/academy/qr-attendance': typeof AuthenticatedAdminAcademyQrAttendanceRoute
  '/_authenticated/admin/academy/receipts': typeof AuthenticatedAdminAcademyReceiptsRoute
  '/_authenticated/admin/academy/reports': typeof AuthenticatedAdminAcademyReportsRoute
  '/_authenticated/admin/academy/schedule': typeof AuthenticatedAdminAcademyScheduleRoute
  '/_authenticated/admin/academy/settings': typeof AuthenticatedAdminAcademySettingsRoute
  '/_authenticated/admin/academy/subscriptions': typeof AuthenticatedAdminAcademySubscriptionsRoute
  '/_authenticated/admin/settings/theme': typeof AuthenticatedAdminSettingsThemeRoute
  '/_authenticated/admin/academy/': typeof AuthenticatedAdminAcademyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/courses'
    | '/join'
    | '/media'
    | '/partners'
    | '/programs'
    | '/admin'
    | '/admin/academy'
    | '/admin/branches'
    | '/admin/courses'
    | '/admin/media'
    | '/admin/notifications'
    | '/admin/partners'
    | '/admin/pipeline'
    | '/admin/posts'
    | '/admin/reports'
    | '/admin/seasons'
    | '/admin/settings'
    | '/admin/submissions'
    | '/admin/users'
    | '/admin/'
    | '/admin/academy/ai-agents'
    | '/admin/academy/analytics'
    | '/admin/academy/assessments'
    | '/admin/academy/attendance'
    | '/admin/academy/branch-reports'
    | '/admin/academy/branches'
    | '/admin/academy/capacity'
    | '/admin/academy/clients'
    | '/admin/academy/coaches'
    | '/admin/academy/finance'
    | '/admin/academy/groups'
    | '/admin/academy/hr'
    | '/admin/academy/hr-reports'
    | '/admin/academy/inventory'
    | '/admin/academy/lane-log'
    | '/admin/academy/lanes'
    | '/admin/academy/leads'
    | '/admin/academy/maintenance'
    | '/admin/academy/permissions'
    | '/admin/academy/pool-operations'
    | '/admin/academy/pools'
    | '/admin/academy/procurement'
    | '/admin/academy/qr-attendance'
    | '/admin/academy/receipts'
    | '/admin/academy/reports'
    | '/admin/academy/schedule'
    | '/admin/academy/settings'
    | '/admin/academy/subscriptions'
    | '/admin/settings/theme'
    | '/admin/academy/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/courses'
    | '/join'
    | '/media'
    | '/partners'
    | '/programs'
    | '/admin/branches'
    | '/admin/courses'
    | '/admin/media'
    | '/admin/notifications'
    | '/admin/partners'
    | '/admin/pipeline'
    | '/admin/posts'
    | '/admin/reports'
    | '/admin/seasons'
    | '/admin/settings'
    | '/admin/submissions'
    | '/admin/users'
    | '/admin'
    | '/admin/academy/ai-agents'
    | '/admin/academy/analytics'
    | '/admin/academy/assessments'
    | '/admin/academy/attendance'
    | '/admin/academy/branch-reports'
    | '/admin/academy/branches'
    | '/admin/academy/capacity'
    | '/admin/academy/clients'
    | '/admin/academy/coaches'
    | '/admin/academy/finance'
    | '/admin/academy/groups'
    | '/admin/academy/hr'
    | '/admin/academy/hr-reports'
    | '/admin/academy/inventory'
    | '/admin/academy/lane-log'
    | '/admin/academy/lanes'
    | '/admin/academy/leads'
    | '/admin/academy/maintenance'
    | '/admin/academy/permissions'
    | '/admin/academy/pool-operations'
    | '/admin/academy/pools'
    | '/admin/academy/procurement'
    | '/admin/academy/qr-attendance'
    | '/admin/academy/receipts'
    | '/admin/academy/reports'
    | '/admin/academy/schedule'
    | '/admin/academy/settings'
    | '/admin/academy/subscriptions'
    | '/admin/settings/theme'
    | '/admin/academy'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/courses'
    | '/join'
    | '/media'
    | '/partners'
    | '/programs'
    | '/_authenticated/admin'
    | '/_authenticated/admin/academy'
    | '/_authenticated/admin/branches'
    | '/_authenticated/admin/courses'
    | '/_authenticated/admin/media'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/partners'
    | '/_authenticated/admin/pipeline'
    | '/_authenticated/admin/posts'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/seasons'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/submissions'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/academy/ai-agents'
    | '/_authenticated/admin/academy/analytics'
    | '/_authenticated/admin/academy/assessments'
    | '/_authenticated/admin/academy/attendance'
    | '/_authenticated/admin/academy/branch-reports'
    | '/_authenticated/admin/academy/branches'
    | '/_authenticated/admin/academy/capacity'
    | '/_authenticated/admin/academy/clients'
    | '/_authenticated/admin/academy/coaches'
    | '/_authenticated/admin/academy/finance'
    | '/_authenticated/admin/academy/groups'
    | '/_authenticated/admin/academy/hr'
    | '/_authenticated/admin/academy/hr-reports'
    | '/_authenticated/admin/academy/inventory'
    | '/_authenticated/admin/academy/lane-log'
    | '/_authenticated/admin/academy/lanes'
    | '/_authenticated/admin/academy/leads'
    | '/_authenticated/admin/academy/maintenance'
    | '/_authenticated/admin/academy/permissions'
    | '/_authenticated/admin/academy/pool-operations'
    | '/_authenticated/admin/academy/pools'
    | '/_authenticated/admin/academy/procurement'
    | '/_authenticated/admin/academy/qr-attendance'
    | '/_authenticated/admin/academy/receipts'
    | '/_authenticated/admin/academy/reports'
    | '/_authenticated/admin/academy/schedule'
    | '/_authenticated/admin/academy/settings'
    | '/_authenticated/admin/academy/subscriptions'
    | '/_authenticated/admin/settings/theme'
    | '/_authenticated/admin/academy/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRoute
  JoinRoute: typeof JoinRoute
  MediaRoute: typeof MediaRoute
  PartnersRoute: typeof PartnersRoute
  ProgramsRoute: typeof ProgramsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/academy': {
      id: '/_authenticated/admin/academy'
      path: '/academy'
      fullPath: '/admin/academy'
      preLoaderRoute: typeof AuthenticatedAdminAcademyRouteRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/branches': {
      id: '/_authenticated/admin/branches'
      path: '/branches'
      fullPath: '/admin/branches'
      preLoaderRoute: typeof AuthenticatedAdminBranchesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/courses': {
      id: '/_authenticated/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AuthenticatedAdminCoursesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/media': {
      id: '/_authenticated/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AuthenticatedAdminMediaRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/partners': {
      id: '/_authenticated/admin/partners'
      path: '/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AuthenticatedAdminPartnersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/pipeline': {
      id: '/_authenticated/admin/pipeline'
      path: '/pipeline'
      fullPath: '/admin/pipeline'
      preLoaderRoute: typeof AuthenticatedAdminPipelineRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/posts': {
      id: '/_authenticated/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AuthenticatedAdminPostsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/seasons': {
      id: '/_authenticated/admin/seasons'
      path: '/seasons'
      fullPath: '/admin/seasons'
      preLoaderRoute: typeof AuthenticatedAdminSeasonsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/submissions': {
      id: '/_authenticated/admin/submissions'
      path: '/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AuthenticatedAdminSubmissionsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/academy/': {
      id: '/_authenticated/admin/academy/'
      path: '/'
      fullPath: '/admin/academy/'
      preLoaderRoute: typeof AuthenticatedAdminAcademyIndexRouteImport
      parentRoute: typeof AuthenticatedAdminAcademyRouteRoute
    }
    '/_authenticated/admin/academy/ai-agents': {
      id: '/_authenticated/admin/academy/ai-agents'
      path: '/ai-agents'
      fullPath: '/admin/academy/ai-agents'
      preLoaderRoute: typeof AuthenticatedAdminAcademyAiAgentsRouteImport
      parentRoute: typeof AuthenticatedAdminAcademyRouteRoute
    }
    '/_authenticated/admin/academy/analytics': {
      id: '/_authenticated/admin/academy/analytics'
      path: '/analytics'
      fullPath: '/admin/academy/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAcademyAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminAcademyRouteRoute
    }
    '/_authenticated/admin/academy/assessments': {
      id: '/_authenticated/admin/academy/assessments'
      path: '/assessments'
      fullPath: '/admin/academy/assessments'
      preLoaderRoute: typeof AuthenticatedAdminAcademyAssessmentsRouteImport
      parentRoute: typeof AuthenticatedAdminAcademyRouteRoute
    }
    '/_authenticated/admin/academy/attendance': {
      id: '/_authenticated/admin/academy/attendance'
      path: '/attendance'
      fullPath: '/admin/academy/attendance'
      preLoaderRoute: typeof AuthenticatedAdminAcademyAttendanceRouteImport
      parentRoute: typeof AuthenticatedAdminAcademyRouteRoute
    }
    '/_authenticated/admin/academy/branch-reports': {
      id: '/_authenticated/admin/academy/branch-reports'
      path: '/branch-reports'
      fullPath: '/admin/academy/branch-reports'
      preLoaderRoute: typeof AuthenticatedAdminAcademyBranchReportsRouteImport
      parentRoute: typeof AuthenticatedAdminAcademyRouteRoute
    }
    '/_authenticated/admin/academy/branches': {
      id: '/_authenticated/admin/academy/branches'
      path: '/branches'
      fullPath: '/admin/academy/branches'
      preLoaderRoute: typeof AuthenticatedAdminAcademyBranchesRouteImport
      parentRoute: typeof AuthenticatedAdminAcademyRouteRoute
    }
    '/_authenticated/admin/academy/capacity': {
      id: '/_authenticated/admin/academy/capacity'
      path: '/capacity'
      fullPath: '/admin/academy/capacity'
      preLoaderRoute: typeof AuthenticatedAdminAcademyCapacityRouteImport
      parentRoute: typeof AuthenticatedAdminAcademyRouteRoute
    }
    '/_authenticated/admin/academy/clients': {
      id: '/_authenticated/admin/academy/clients'
      path: '/clients'
      fullPath: '/admin/academy/clients'
      preLoaderRoute: typeof AuthenticatedAdminAcademyClientsRouteImport
      parentRoute: typeof AuthenticatedAdminAcademyRouteRoute
    }
    '/_authenticated/admin/academy/coaches': {
      id: '/_authenticated/admin/academy/coaches'
      path: '/coaches'
      fullPath: '/admin/academy/coaches'
      preLoaderRoute: typeof AuthenticatedAdminAcademyCoachesRouteImport
      parentRoute: typeof AuthenticatedAdminAcademyRouteRoute
    }
    '/_authenticated/admin/academy/finance': {
      id: '/_authenticated/admin/academy/finance'
      path: '/finance'
      fullPath: '/admin/academy/finance'
      preLoaderRoute: typeof AuthenticatedAdminAcademyFinanceRouteImport
      parentRoute: typeof AuthenticatedAdminAcademyRouteRoute
    }
    '/_authenticated/admin/academy/groups': {
      id: '/_authenticated/admin/academy/groups'
      path: '/groups'
      fullPath: '/admin/academy/groups'
      preLoaderRoute: typeof AuthenticatedAdminAcademyGroupsRouteImport
      parentRoute: typeof AuthenticatedAdminAcademyRouteRoute
    }
    '/_authenticated/admin/academy/hr': {
      id: '/_authenticated/admin/academy/hr'
      path: '/hr'
      fullPath: '/admin/academy/hr'
      preLoaderRoute: typeof AuthenticatedAdminAcademyHrRouteImport
      parentRoute: typeof AuthenticatedAdminAcademyRouteRoute
    }
    '/_authenticated/admin/academy/hr-reports': {
      id: '/_authenticated/admin/academy/hr-reports'
      path: '/hr-reports'
      fullPath: '/admin/academy/hr-reports'
      preLoaderRoute: typeof AuthenticatedAdminAcademyHrReportsRouteImport
      parentRoute: typeof AuthenticatedAdminAcademyRouteRoute
    }
    '/_authenticated/admin/academy/inventory': {
      id: '/_authenticated/admin/academy/inventory'
      path: '/inventory'
      fullPath: '/admin/academy/inventory'
      preLoaderRoute: typeof AuthenticatedAdminAcademyInventoryRouteImport
      parentRoute: typeof AuthenticatedAdminAcademyRouteRoute
    }
    '/_authenticated/admin/academy/lane-log': {
      id: '/_authenticated/admin/academy/lane-log'
      path: '/lane-log'
      fullPath: '/admin/academy/lane-log'
      preLoaderRoute: typeof AuthenticatedAdminAcademyLaneLogRouteImport
      parentRoute: typeof AuthenticatedAdminAcademyRouteRoute
    }
    '/_authenticated/admin/academy/lanes': {
      id: '/_authenticated/admin/academy/lanes'
      path: '/lanes'
      fullPath: '/admin/academy/lanes'
      preLoaderRoute: typeof AuthenticatedAdminAcademyLanesRouteImport
      parentRoute: typeof AuthenticatedAdminAcademyRouteRoute
    }
    '/_authenticated/admin/academy/leads': {
      id: '/_authenticated/admin/academy/leads'
      path: '/leads'
      fullPath: '/admin/academy/leads'
      preLoaderRoute: typeof AuthenticatedAdminAcademyLeadsRouteImport
      parentRoute: typeof AuthenticatedAdminAcademyRouteRoute
    }
    '/_authenticated/admin/academy/maintenance': {
      id: '/_authenticated/admin/academy/maintenance'
      path: '/maintenance'
      fullPath: '/admin/academy/maintenance'
      preLoaderRoute: typeof AuthenticatedAdminAcademyMaintenanceRouteImport
      parentRoute: typeof AuthenticatedAdminAcademyRouteRoute
    }
    '/_authenticated/admin/academy/permissions': {
      id: '/_authenticated/admin/academy/permissions'
      path: '/permissions'
      fullPath: '/admin/academy/permissions'
      preLoaderRoute: typeof AuthenticatedAdminAcademyPermissionsRouteImport
      parentRoute: typeof AuthenticatedAdminAcademyRouteRoute
    }
    '/_authenticated/admin/academy/pool-operations': {
      id: '/_authenticated/admin/academy/pool-operations'
      path: '/pool-operations'
      fullPath: '/admin/academy/pool-operations'
      preLoaderRoute: typeof AuthenticatedAdminAcademyPoolOperationsRouteImport
      parentRoute: typeof AuthenticatedAdminAcademyRouteRoute
    }
    '/_authenticated/admin/academy/pools': {
      id: '/_authenticated/admin/academy/pools'
      path: '/pools'
      fullPath: '/admin/academy/pools'
      preLoaderRoute: typeof AuthenticatedAdminAcademyPoolsRouteImport
      parentRoute: typeof AuthenticatedAdminAcademyRouteRoute
    }
    '/_authenticated/admin/academy/procurement': {
      id: '/_authenticated/admin/academy/procurement'
      path: '/procurement'
      fullPath: '/admin/academy/procurement'
      preLoaderRoute: typeof AuthenticatedAdminAcademyProcurementRouteImport
      parentRoute: typeof AuthenticatedAdminAcademyRouteRoute
    }
    '/_authenticated/admin/academy/qr-attendance': {
      id: '/_authenticated/admin/academy/qr-attendance'
      path: '/qr-attendance'
      fullPath: '/admin/academy/qr-attendance'
      preLoaderRoute: typeof AuthenticatedAdminAcademyQrAttendanceRouteImport
      parentRoute: typeof AuthenticatedAdminAcademyRouteRoute
    }
    '/_authenticated/admin/academy/receipts': {
      id: '/_authenticated/admin/academy/receipts'
      path: '/receipts'
      fullPath: '/admin/academy/receipts'
      preLoaderRoute: typeof AuthenticatedAdminAcademyReceiptsRouteImport
      parentRoute: typeof AuthenticatedAdminAcademyRouteRoute
    }
    '/_authenticated/admin/academy/reports': {
      id: '/_authenticated/admin/academy/reports'
      path: '/reports'
      fullPath: '/admin/academy/reports'
      preLoaderRoute: typeof AuthenticatedAdminAcademyReportsRouteImport
      parentRoute: typeof AuthenticatedAdminAcademyRouteRoute
    }
    '/_authenticated/admin/academy/schedule': {
      id: '/_authenticated/admin/academy/schedule'
      path: '/schedule'
      fullPath: '/admin/academy/schedule'
      preLoaderRoute: typeof AuthenticatedAdminAcademyScheduleRouteImport
      parentRoute: typeof AuthenticatedAdminAcademyRouteRoute
    }
    '/_authenticated/admin/academy/settings': {
      id: '/_authenticated/admin/academy/settings'
      path: '/settings'
      fullPath: '/admin/academy/settings'
      preLoaderRoute: typeof AuthenticatedAdminAcademySettingsRouteImport
      parentRoute: typeof AuthenticatedAdminAcademyRouteRoute
    }
    '/_authenticated/admin/academy/subscriptions': {
      id: '/_authenticated/admin/academy/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/academy/subscriptions'
      preLoaderRoute: typeof AuthenticatedAdminAcademySubscriptionsRouteImport
      parentRoute: typeof AuthenticatedAdminAcademyRouteRoute
    }
    '/_authenticated/admin/settings/theme': {
      id: '/_authenticated/admin/settings/theme'
      path: '/theme'
      fullPath: '/admin/settings/theme'
      preLoaderRoute: typeof AuthenticatedAdminSettingsThemeRouteImport
      parentRoute: typeof AuthenticatedAdminSettingsRoute
    }
  }
}

interface AuthenticatedAdminAcademyRouteRouteChildren {
  AuthenticatedAdminAcademyAiAgentsRoute: typeof AuthenticatedAdminAcademyAiAgentsRoute
  AuthenticatedAdminAcademyAnalyticsRoute: typeof AuthenticatedAdminAcademyAnalyticsRoute
  AuthenticatedAdminAcademyAssessmentsRoute: typeof AuthenticatedAdminAcademyAssessmentsRoute
  AuthenticatedAdminAcademyAttendanceRoute: typeof AuthenticatedAdminAcademyAttendanceRoute
  AuthenticatedAdminAcademyBranchReportsRoute: typeof AuthenticatedAdminAcademyBranchReportsRoute
  AuthenticatedAdminAcademyBranchesRoute: typeof AuthenticatedAdminAcademyBranchesRoute
  AuthenticatedAdminAcademyCapacityRoute: typeof AuthenticatedAdminAcademyCapacityRoute
  AuthenticatedAdminAcademyClientsRoute: typeof AuthenticatedAdminAcademyClientsRoute
  AuthenticatedAdminAcademyCoachesRoute: typeof AuthenticatedAdminAcademyCoachesRoute
  AuthenticatedAdminAcademyFinanceRoute: typeof AuthenticatedAdminAcademyFinanceRoute
  AuthenticatedAdminAcademyGroupsRoute: typeof AuthenticatedAdminAcademyGroupsRoute
  AuthenticatedAdminAcademyHrRoute: typeof AuthenticatedAdminAcademyHrRoute
  AuthenticatedAdminAcademyHrReportsRoute: typeof AuthenticatedAdminAcademyHrReportsRoute
  AuthenticatedAdminAcademyInventoryRoute: typeof AuthenticatedAdminAcademyInventoryRoute
  AuthenticatedAdminAcademyLaneLogRoute: typeof AuthenticatedAdminAcademyLaneLogRoute
  AuthenticatedAdminAcademyLanesRoute: typeof AuthenticatedAdminAcademyLanesRoute
  AuthenticatedAdminAcademyLeadsRoute: typeof AuthenticatedAdminAcademyLeadsRoute
  AuthenticatedAdminAcademyMaintenanceRoute: typeof AuthenticatedAdminAcademyMaintenanceRoute
  AuthenticatedAdminAcademyPermissionsRoute: typeof AuthenticatedAdminAcademyPermissionsRoute
  AuthenticatedAdminAcademyPoolOperationsRoute: typeof AuthenticatedAdminAcademyPoolOperationsRoute
  AuthenticatedAdminAcademyPoolsRoute: typeof AuthenticatedAdminAcademyPoolsRoute
  AuthenticatedAdminAcademyProcurementRoute: typeof AuthenticatedAdminAcademyProcurementRoute
  AuthenticatedAdminAcademyQrAttendanceRoute: typeof AuthenticatedAdminAcademyQrAttendanceRoute
  AuthenticatedAdminAcademyReceiptsRoute: typeof AuthenticatedAdminAcademyReceiptsRoute
  AuthenticatedAdminAcademyReportsRoute: typeof AuthenticatedAdminAcademyReportsRoute
  AuthenticatedAdminAcademyScheduleRoute: typeof AuthenticatedAdminAcademyScheduleRoute
  AuthenticatedAdminAcademySettingsRoute: typeof AuthenticatedAdminAcademySettingsRoute
  AuthenticatedAdminAcademySubscriptionsRoute: typeof AuthenticatedAdminAcademySubscriptionsRoute
  AuthenticatedAdminAcademyIndexRoute: typeof AuthenticatedAdminAcademyIndexRoute
}

const AuthenticatedAdminAcademyRouteRouteChildren: AuthenticatedAdminAcademyRouteRouteChildren =
  {
    AuthenticatedAdminAcademyAiAgentsRoute:
      AuthenticatedAdminAcademyAiAgentsRoute,
    AuthenticatedAdminAcademyAnalyticsRoute:
      AuthenticatedAdminAcademyAnalyticsRoute,
    AuthenticatedAdminAcademyAssessmentsRoute:
      AuthenticatedAdminAcademyAssessmentsRoute,
    AuthenticatedAdminAcademyAttendanceRoute:
      AuthenticatedAdminAcademyAttendanceRoute,
    AuthenticatedAdminAcademyBranchReportsRoute:
      AuthenticatedAdminAcademyBranchReportsRoute,
    AuthenticatedAdminAcademyBranchesRoute:
      AuthenticatedAdminAcademyBranchesRoute,
    AuthenticatedAdminAcademyCapacityRoute:
      AuthenticatedAdminAcademyCapacityRoute,
    AuthenticatedAdminAcademyClientsRoute:
      AuthenticatedAdminAcademyClientsRoute,
    AuthenticatedAdminAcademyCoachesRoute:
      AuthenticatedAdminAcademyCoachesRoute,
    AuthenticatedAdminAcademyFinanceRoute:
      AuthenticatedAdminAcademyFinanceRoute,
    AuthenticatedAdminAcademyGroupsRoute: AuthenticatedAdminAcademyGroupsRoute,
    AuthenticatedAdminAcademyHrRoute: AuthenticatedAdminAcademyHrRoute,
    AuthenticatedAdminAcademyHrReportsRoute:
      AuthenticatedAdminAcademyHrReportsRoute,
    AuthenticatedAdminAcademyInventoryRoute:
      AuthenticatedAdminAcademyInventoryRoute,
    AuthenticatedAdminAcademyLaneLogRoute:
      AuthenticatedAdminAcademyLaneLogRoute,
    AuthenticatedAdminAcademyLanesRoute: AuthenticatedAdminAcademyLanesRoute,
    AuthenticatedAdminAcademyLeadsRoute: AuthenticatedAdminAcademyLeadsRoute,
    AuthenticatedAdminAcademyMaintenanceRoute:
      AuthenticatedAdminAcademyMaintenanceRoute,
    AuthenticatedAdminAcademyPermissionsRoute:
      AuthenticatedAdminAcademyPermissionsRoute,
    AuthenticatedAdminAcademyPoolOperationsRoute:
      AuthenticatedAdminAcademyPoolOperationsRoute,
    AuthenticatedAdminAcademyPoolsRoute: AuthenticatedAdminAcademyPoolsRoute,
    AuthenticatedAdminAcademyProcurementRoute:
      AuthenticatedAdminAcademyProcurementRoute,
    AuthenticatedAdminAcademyQrAttendanceRoute:
      AuthenticatedAdminAcademyQrAttendanceRoute,
    AuthenticatedAdminAcademyReceiptsRoute:
      AuthenticatedAdminAcademyReceiptsRoute,
    AuthenticatedAdminAcademyReportsRoute:
      AuthenticatedAdminAcademyReportsRoute,
    AuthenticatedAdminAcademyScheduleRoute:
      AuthenticatedAdminAcademyScheduleRoute,
    AuthenticatedAdminAcademySettingsRoute:
      AuthenticatedAdminAcademySettingsRoute,
    AuthenticatedAdminAcademySubscriptionsRoute:
      AuthenticatedAdminAcademySubscriptionsRoute,
    AuthenticatedAdminAcademyIndexRoute: AuthenticatedAdminAcademyIndexRoute,
  }

const AuthenticatedAdminAcademyRouteRouteWithChildren =
  AuthenticatedAdminAcademyRouteRoute._addFileChildren(
    AuthenticatedAdminAcademyRouteRouteChildren,
  )

interface AuthenticatedAdminSettingsRouteChildren {
  AuthenticatedAdminSettingsThemeRoute: typeof AuthenticatedAdminSettingsThemeRoute
}

const AuthenticatedAdminSettingsRouteChildren: AuthenticatedAdminSettingsRouteChildren =
  {
    AuthenticatedAdminSettingsThemeRoute: AuthenticatedAdminSettingsThemeRoute,
  }

const AuthenticatedAdminSettingsRouteWithChildren =
  AuthenticatedAdminSettingsRoute._addFileChildren(
    AuthenticatedAdminSettingsRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAcademyRouteRoute: typeof AuthenticatedAdminAcademyRouteRouteWithChildren
  AuthenticatedAdminBranchesRoute: typeof AuthenticatedAdminBranchesRoute
  AuthenticatedAdminCoursesRoute: typeof AuthenticatedAdminCoursesRoute
  AuthenticatedAdminMediaRoute: typeof AuthenticatedAdminMediaRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminPartnersRoute: typeof AuthenticatedAdminPartnersRoute
  AuthenticatedAdminPipelineRoute: typeof AuthenticatedAdminPipelineRoute
  AuthenticatedAdminPostsRoute: typeof AuthenticatedAdminPostsRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminSeasonsRoute: typeof AuthenticatedAdminSeasonsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRouteWithChildren
  AuthenticatedAdminSubmissionsRoute: typeof AuthenticatedAdminSubmissionsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAcademyRouteRoute:
      AuthenticatedAdminAcademyRouteRouteWithChildren,
    AuthenticatedAdminBranchesRoute: AuthenticatedAdminBranchesRoute,
    AuthenticatedAdminCoursesRoute: AuthenticatedAdminCoursesRoute,
    AuthenticatedAdminMediaRoute: AuthenticatedAdminMediaRoute,
    AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
    AuthenticatedAdminPartnersRoute: AuthenticatedAdminPartnersRoute,
    AuthenticatedAdminPipelineRoute: AuthenticatedAdminPipelineRoute,
    AuthenticatedAdminPostsRoute: AuthenticatedAdminPostsRoute,
    AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
    AuthenticatedAdminSeasonsRoute: AuthenticatedAdminSeasonsRoute,
    AuthenticatedAdminSettingsRoute:
      AuthenticatedAdminSettingsRouteWithChildren,
    AuthenticatedAdminSubmissionsRoute: AuthenticatedAdminSubmissionsRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRoute,
  JoinRoute: JoinRoute,
  MediaRoute: MediaRoute,
  PartnersRoute: PartnersRoute,
  ProgramsRoute: ProgramsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
